spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/music
    username: ${PSQL_USER}
    password: ${PSQL_PASS}

  jpa:
    hibernate:
      ddl-auto: validate
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect